config/routes.rb
# coding: UTF-8
require 'release_type'

AntCat::Application.routes.draw do

  root to: "catalog/index#show"

  resources :authors, only: [:index, :all, :merge]
  match     '/authors/all', to: 'authors#all', via: :get
  match     '/authors/merge', to: 'authors#merge', via: :post
  resources :bolton_references
  resource  :catalog, only: [] do
    match     'index/(:id)', to: 'catalog/index#show', as: 'index'
    match     'browser/(:id)', to: 'catalog/browser#show', as: 'browser'
  end
  match     '/documents/:id/:file_name', to: 'references#download', file_name: /.+/, via: :get
  resources :journals
  resources :publishers, only: [:index]
  resources :references, only: [:index, :update, :create, :destroy]
  match     '/antcat_references.utf8.endnote_import', to: 'references#index', format: :endnote_import, as: :endnote_import
  resources :styles, only: [:index]

  resources :families, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :subfamilies, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :tribes, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :genera, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :subgenera, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :species, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :subspecies, controller: :catalog do
    resources :taxonomic_history_items
  end

  resource :reference_picker, only: :show

  match '/widget_tests/reference_picker', to: 'widget_tests#reference_picker'

  devise_for :users

end

app/views/shared/_catalog_title.html.haml
.title
  %h2.left An Online Catalog of the Ants of the World
  .right
    %h3
      by Barry Bolton
      %span.date 1 Jan 2012
  .clear

app/views/shared/_coins.html.haml
= coins reference

app/views/shared/_errors_for.html.haml
- if resource.errors.present?
  %ul.error_messages
    - for error in resource.errors.full_messages
      %li= error

app/views/shared/_login.html.haml
#login
  - items = []
  .link
    - if user_signed_in?
      - items << link_to(current_user.email, edit_user_registration_path)
      - items << link_to('Logout', destroy_user_session_path)
    - else
      - items << link_to('Login', '#', class: :link)
    - items << feedback_link
    = make_link_menu items

  .form
    = form_tag user_session_path do
      Email
      = text_field_tag "user[email]"
      Password
      = password_field_tag "user[password]"
      = submit_tag "Go"
      %br
      %span.small
        = make_link_menu check_box_tag("user[remember_me]", "1", true) + "Remember me ",  link_to('Forgot password?', new_user_password_path), link_to('Cancel', '#', class: :link)

app/views/shared/_qtip.html.haml
.qtip
  .qtip-tip
  .qtip-wrapper
    .qtip-contentWrapper
      .qtip-title
        .qtip-button
      .qtip-content

app/views/shared/_search.html.haml
- content_for :nav do
  .nav_bg{:style => "z-index:3000;"}
    %form#search_form{:action => '/references', :method => 'get'}
      .header_left#nav
        %a{:href => "/references?commit=new"} Show latest additions
        - if user_signed_in?
          %span
            |
          %a{:href => "/references?commit=review"} Show latest changes
          %span
            |
          %a{:href => "/journals"} Edit journals
      .header_search
        %b Search for
        %input.header_search_input{:type => "text", :name => "q", :value => params[:q], :style => "height:20px;"}
        %input.header_search_submit{:type => "submit", :name => "commit", :value => "Go &#187;"}

app/views/shared/_site_footer.html.haml
%table.images
  %tr
    %td
      = link_to 'http://www.calacademy.org/', target: '_blank' do
        = image_tag 'calacademy.gif', style: "height: 40px"
    %td.spacer
    %td
      = link_to 'http://www.nsf.gov/', target: '_blank' do
        = image_tag 'nsf1.gif', style: "height: 50px", title: "Supported in part by NSF Award DBI-0642321"
    %td.spacer
    %td
      = link_to 'http://rubyonrails.org/', target: '_blank' do
        = image_tag 'rails.png', style: "height: 40px"
    %td.spacer
    %td
      = link_to 'http://antweb.org', target: '_blank' do
        = image_tag 'antweb_logo_tiny.png', style: "height: 20px"
    %td.spacer
    %td
      = link_to 'http://hol.osu.edu/', target: '_blank' do
        = image_tag 'hol.png', style: "height: 20px"
    %td.spacer
    %td
      = link_to 'http://antbase.org/', target: '_blank' do
        = image_tag 'antbase.org.png', style: "height: 20px"
    %td.spacer
    %td
      = link_to 'http://www.zotero.org/', target: '_blank' do
        = image_tag 'zotero_logo_tiny.png', style: "height: 20px"

app/views/shared/_site_header.html.haml
.logo
  = link_to root_path do
    = image_tag 'antcat_logo.png', :alt => "AntCat"
  = release_type_indicator

.image
  = image_tag 'site_header_ant_5.png', :name => "imgs"

.navigation
  = render 'shared/login'
  = make_link_menu link_to('Catalog', index_catalog_path), |
                   link_to('References', references_path), |
                   link_to('Authors', authors_path), |
                   link_to('AntWeb', "http://www.antweb.org/") |