config/routes.rb
# coding: UTF-8
require 'release_type'

AntCat::Application.routes.draw do

  root to: "catalog/index#show"

  resources :authors, only: [:index, :all, :merge]
  match     '/authors/all', to: 'authors#all', via: :get
  match     '/authors/merge', to: 'authors#merge', via: :post
  resources :bolton_references
  resource  :catalog, only: [] do
    match     'index/(:id)', to: 'catalog/index#show', as: 'index'
    match     'browser/(:id)', to: 'catalog/browser#show', as: 'browser'
  end
  match     '/documents/:id/:file_name', to: 'references#download', file_name: /.+/, via: :get
  resources :journals
  resources :publishers, only: [:index]
  resources :references, only: [:index, :update, :create, :destroy]
  match     '/antcat_references.utf8.endnote_import', to: 'references#index', format: :endnote_import, as: :endnote_import
  resources :styles, only: [:index]

  resources :families, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :subfamilies, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :tribes, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :genera, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :subgenera, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :species, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :subspecies, controller: :catalog do
    resources :taxonomic_history_items
  end

  resource :reference_picker, only: :show

  match '/widget_tests/reference_picker', to: 'widget_tests#reference_picker'

  devise_for :users

end

app/controllers/reference_pickers_controller.rb
# coding: UTF-8
class ReferencePickersController < ApplicationController

  def show
    params[:search_selector] ||= 'Search for author(s)'

    if params[:id].present?
      @references = Reference.perform_search id: params[:id]
      @current_reference = @references.first
    end

    if params[:q].present?
      params[:q].strip!
      params[:is_author_search] = params[:search_selector] == 'Search for author(s)'
      @references = Reference.do_search params
    end

    render partial: 'show', locals: {current_reference: @current_reference, references: @references}
  end

end

app/views/reference_pickers/_create.html.haml
= form_tag reference_pickers_path, id: 'search_form' do
  = button_tag 'OK', class: 'ok'
  = button_tag 'Cancel', class: 'close'
  = select_tag "search_selector", options_for_select(["Search for", "Search for author(s)"], params[:search_selector])
  = text_field_tag "q", params[:q]
  = image_tag 'help.png', class: 'help_icon'
  = submit_tag 'Go'

-if @references.empty?
  .no_results_found
    No results found

%table.references
  - for reference in @references
    %tr.reference_row
      %td
        = render 'reference', :reference => reference, :publisher_string => '', :css_class => 'reference'

%div= will_paginate @references

= render 'shared/qtip'

app/views/reference_pickers/_display.html.haml
- css_class = 'reference_display'
- css_class << ' downloadable' if reference.downloadable_by? current_user
%div{:class => css_class}
  = raw format_reference reference
  - document_link = format_reference_document_link reference
  = raw document_link if document_link
  = reference.id

  %p.notes= italicize h reference.public_notes
  - if user_is_editor?
    %p.editor.notes= italicize h reference.editor_notes
    %p.notes= italicize h reference.taxonomic_notes

app/views/reference_pickers/_edit.html.haml
- reference ||= Reference.new
- publisher_string ||= reference.respond_to?(:publisher) ? (reference.publisher && reference.publisher.to_s) : ''
- journal_name = reference.respond_to?(:journal) ? (reference.journal && reference.journal.name) : ''
- selected_tab = [ArticleReference, BookReference, NestedReference, UnknownReference].index(reference.class) || 0

.reference_edit.ui-corner-all.ui-widget-content.ui-widget
  - url = reference.new_record? ? references_path(picker: true) : reference_path(reference, picker: true)
  - method = reference.new_record? ? 'post' : 'put'
  - html_options = Rails.env.test? ? {} : {:multipart => true}
  = form_for reference, :as => :reference, :url => url, :html => html_options do |f|
    %input{:type => 'hidden', :name => '_method', :value => method}
    %input{type: :hidden, name: :selected_tab, id: :selected_tab, class: :selected_tab, value: selected_tab}
    %input{type: 'hidden', name: 'possible_duplicate', id: 'possible_duplicate', value: @possible_duplicate ? 'true' : nil}
    = render 'shared/errors_for', :resource => reference

    %table
      %col{:width => '50px'}
      %col{:width => '*'}
      %col{:align => 'right', :width => '34px'}
      %col{:width => '100px'}
      %tr
        %td= label_tag :reference_author_names_string, 'Authors'
        %td.authors= f.text_field :author_names_string, :class => 'authors'
        %td{:style => 'padding-right: 5px'}= label_tag :reference_citation_year, 'Year'
        %td{:class => :right_side_field}= f.text_field :citation_year
      %tr
        %td= label_tag :reference_title, 'Title'
        %td{:colspan => 3, :class => :right_side_field}= f.text_area :title, :rows => 2
      %tr
        %td.tabs{:colspan => 4}

          .tabbable{'data-title' => 'Article'}
            = label_tag :journal_name, 'Journal'
            = text_field_tag :journal_name, journal_name, :class => 'journal'
            = label_tag :reference_series_volume_issue, 'Series volume issue'
            = f.text_field :series_volume_issue, :class => 'series_volume_issue'
            = label_tag :article_pagination, 'Pagination'
            = text_field_tag :article_pagination, reference.pagination, :class => 'pages'

          .tabbable{'data-title' => 'Book'}
            = label_tag :publisher_string, 'Publisher'
            = text_field_tag :publisher_string, publisher_string, :class => 'publisher'
            = label_tag :book_pagination, 'Pagination'
            = text_field_tag :book_pagination, reference.pagination, :class => 'pages'

          .tabbable{'data-title' => 'Nested'}
            = label_tag :reference_pages_in, 'Pages in'
            = f.text_field :pages_in, :class => 'pages'
            = label_tag :reference_nested_reference_id, 'Nested reference ID'
            = f.text_field :nested_reference_id, :class => 'pages'
            %p.help
              %span.help= raw "To find, edit or add the nested reference in a new browser window, click #{link_to 'here', references_path(:q => reference.nested_reference_id), :target => '_blank'}"

          .tabbable{'data-title' => 'Other'}
            = label_tag :reference_citation, 'Citation'
            = f.text_area :citation, :rows => 2

      = f.fields_for :document, reference.document || ReferenceDocument.new do |document_form|
        %tr
          %td= label_tag :document_url, 'Source URL'
          %td{:colspan => 3, :class => :right_side_field}
            = document_form.text_field :url
            = label_tag :document_public, 'Internal but public?'
            = document_form.check_box :public
        - unless $ReleaseType.preview?
          %tr
            %td= label_tag :document_file, 'Upload'
            %td= document_form.file_field :file

      %tr
        %td= label_tag :reference_public_notes, 'Public notes'
        %td{:colspan => 3, :class => :right_side_field}= f.text_area :public_notes, :rows => 2
      - if user_is_editor?
        %tr
          %td= label_tag :reference_editor_notes, 'Editor notes'
          %td{:colspan => 3, :class => :right_side_field}= f.text_area :editor_notes, :rows => 2
        %tr
          %td= label_tag :reference_taxonomic_notes, 'Taxonomic notes'
          %td{:colspan => 3, :class => :right_side_field}= f.text_area :taxonomic_notes, :rows => 2
      %tr
        %td{:colspan => 4}
          %table.small_fields
            %tr
              %td{:style => 'padding-right: 5px'}= label_tag :reference_cite_code, 'Cite code'
              %td.cite_code= f.text_field :cite_code
              %td= label_tag :reference_possess, 'Possess'
              %td.possess= f.text_field :possess
              %td= label_tag :reference_date, 'Date'
              %td.date= f.text_field :date
              %td= label_tag :reference_id, 'ID'
              %td= reference.id
      %tr
        %td.spinner_container{:colspan => 4}
          %button.ui-priority-primary.submit= @possible_duplicate ? 'Save Anyway' : 'Save'
          %button.ui-priority-secondary.cancel Cancel

app/views/reference_pickers/_reference.html.haml
-#Locals: reference

- reference ||= Reference.new
- css_class = 'reference'
- css_class << " reference_#{reference.id}" if reference.id

%div{class: css_class, 'data-reference-id' => reference.id, 'data-taxt' => Taxt.to_editable_reference(reference)}
  %table.reference_table
    %tr
      %td.icons
        %a.icon.edit{title: 'edit', href: '#'}
          = image_tag 'edit_off.png', alt: 'edit'
      %td.reference_item
        = render 'reference_pickers/display', reference: reference if !reference.new_record? && reference.errors.empty?
        = render 'reference_pickers/edit', reference: reference, publisher_string: publisher_string

app/views/reference_pickers/_show.html.haml
-#Locals: references, current_reference

.template
  = render 'reference', reference: nil, publisher_string: ''

%table.current_reference.references
  %tr.reference_row
    %td
      - if current_reference
        = render 'reference', reference: current_reference, publisher_string: '', css_class: 'reference'

= form_tag reference_picker_path, class: 'search_form' do
  -# this table is to provide a fixed-width column for the throbber beside
  -# a variable width and height column for the controls
  %table
    %tr
      %td.throbber= image_tag 'ui-anim_basic_16x16.gif'
      %td
        .ok_cancel_controls
          = button_tag 'OK', class: 'ok ui-priority-primary'
          = button_tag 'Cancel', class: 'close ui-priority-secondary'

        .add_controls
          = button_tag 'Add', class: 'add ui-priority-primary'

        .search_controls
          = select_tag "search_selector", options_for_select(["Search for", "Search for author(s)"], params[:search_selector]), class: 'search_selector'
          = text_field_tag "q", params[:q], class: 'q'
          = button_tag 'Go', class: 'ui-priority-primary'
          = button_tag 'Cancel', class: 'ui-priority-secondary close'

        = will_paginate references if references

        .help_banner
          %span.help_banner_text

- if references && (references.first != current_reference || references.size != 1 || params[:q].present?)

  -if references.empty?
    .no_results_found No results found

  %table.references.search_results
    - for reference in references
      %tr.reference_row
        %td= render 'reference', reference: reference, publisher_string: '', css_class: 'reference'

= render 'shared/qtip'