config/routes.rb
# coding: UTF-8
require 'release_type'

AntCat::Application.routes.draw do

  root to: "catalog/index#show"

  resources :authors, only: [:index, :all, :merge]
  match     '/authors/all', to: 'authors#all', via: :get
  match     '/authors/merge', to: 'authors#merge', via: :post
  resources :bolton_references
  resource  :catalog, only: [] do
    match     'index/(:id)', to: 'catalog/index#show', as: 'index'
    match     'browser/(:id)', to: 'catalog/browser#show', as: 'browser'
  end
  match     '/documents/:id/:file_name', to: 'references#download', file_name: /.+/, via: :get
  resources :journals
  resources :publishers, only: [:index]
  resources :references, only: [:index, :update, :create, :destroy]
  match     '/antcat_references.utf8.endnote_import', to: 'references#index', format: :endnote_import, as: :endnote_import
  resources :styles, only: [:index]

  resources :families, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :subfamilies, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :tribes, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :genera, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :subgenera, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :species, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :subspecies, controller: :catalog do
    resources :taxonomic_history_items
  end

  resource :reference_picker, only: :show

  match '/widget_tests/reference_picker', to: 'widget_tests#reference_picker'

  devise_for :users

end

app/models/journal.rb
# coding: UTF-8
class Journal < ActiveRecord::Base

  validates_presence_of :name
  scope :list, order(:name)

  def self.import name
    return unless name.present?
    journal = find_or_create_by_name name
    raise unless journal.valid?
    journal
  end

  def self.search term = ''
    search_expression = term.split('').join('%') + '%'
    select('journals.name, COUNT(*)').
      joins('LEFT OUTER JOIN `references` ON references.journal_id = journals.id').
      where('journals.name LIKE ?', search_expression).
      group('journals.id').
      order('COUNT(*) DESC').
      map(&:name)
  end

end

app/controllers/journals_controller.rb
# coding: UTF-8
class JournalsController < ApplicationController
  before_filter :authenticate_user!
  skip_before_filter :authenticate_user!, :if => :preview?
  before_filter :find_journal, :only => [:edit, :update]

  def index
    respond_to do |format|
      format.html {@journals = Journal.list}
      format.json {render :json => Journal.search(params[:term]).to_json}
    end
  end

  def new
    @journal = Journal.new
  end

  def create
    @journal = Journal.new(params[:journal])
    if @journal.save
      flash[:notice] = "Successfully created journal."
      render :edit
    else
      render :new
    end
  end

  def update
    if @journal.update_attributes(params[:journal])
      flash[:notice] = "Successfully updated journal."
    end
    render :edit, :journal => @journal
  end

  private
  def find_journal
    @journal = Journal.find(params[:id])
  end

end

app/views/journals/_form.html.haml
= form_for journal do |f|
  = render 'shared/errors_for', :resource => journal
  %p
    = f.label :name, 'Journal name'
    %br
    = f.text_field :name
    = f.submit previewize 'Save'
  %p
  %p
    %br

app/views/journals/edit.html.haml
- @title = 'Edit Journal'

= render 'form', :journal => @journal

%h4 References using this journal
- Reference.sorted_by_principal_author_last_name.all(:conditions => ['journal_id = ?', @journal.id]).each do |reference|
  %p.reference_list= "#{format_reference(reference)} #{reference.id}"

app/views/journals/index.html.haml
- @title = 'Journals'

%table
  %tr
  - for journal in @journals
    %tr
      %td= link_to journal.name, edit_journal_path(journal)

%p= button_to "New Journal", new_journal_path, :method => :get

app/views/journals/new.html.haml
- @title = 'Add Journal'

= render 'form', :journal => @journal