config/routes.rb
# coding: UTF-8
require 'release_type'

AntCat::Application.routes.draw do

  root to: "catalog/index#show"

  resources :authors, only: [:index, :all, :merge]
  match     '/authors/all', to: 'authors#all', via: :get
  match     '/authors/merge', to: 'authors#merge', via: :post
  resources :bolton_references
  resource  :catalog, only: [] do
    match     'index/(:id)', to: 'catalog/index#show', as: 'index'
    match     'browser/(:id)', to: 'catalog/browser#show', as: 'browser'
  end
  match     '/documents/:id/:file_name', to: 'references#download', file_name: /.+/, via: :get
  resources :journals
  resources :publishers, only: [:index]
  resources :references, only: [:index, :update, :create, :destroy]
  match     '/antcat_references.utf8.endnote_import', to: 'references#index', format: :endnote_import, as: :endnote_import
  resources :styles, only: [:index]

  resources :families, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :subfamilies, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :tribes, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :genera, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :subgenera, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :species, controller: :catalog do
    resources :taxonomic_history_items
  end
  resources :subspecies, controller: :catalog do
    resources :taxonomic_history_items
  end

  resource :reference_picker, only: :show

  match '/widget_tests/reference_picker', to: 'widget_tests#reference_picker'

  devise_for :users

end

app/models/bolton/reference.rb
# coding: UTF-8
class Bolton::Reference < ActiveRecord::Base
  include ReferenceComparable
  set_table_name :bolton_references

  belongs_to :match, :class_name => '::Reference'
  has_many :matches, :class_name => 'Bolton::Match', :foreign_key => :bolton_reference_id
  has_many :possible_matches, :through => :matches, :source => :reference

  before_validation :set_year
  before_save :set_key_cache

  searchable do
    text :original
    integer :id
  end

  def self.do_search options = {}
    query =
      select('DISTINCT bolton_references.*').
        joins('LEFT OUTER JOIN bolton_matches ON bolton_matches.bolton_reference_id = bolton_references.id').
        paginate(:page => options[:page])

    if options[:match_threshold].present?
      query = query.where 'similarity <= ?', options[:match_threshold]
    end

    if options[:match_statuses].present?
      query_clauses = []
      query_clauses << 'match_status IS NULL' if options[:match_statuses].include? nil
      query_clauses << 'match_status = "auto"' if options[:match_statuses].include? 'auto'
      query_clauses << 'match_status = "manual"' if options[:match_statuses].include? 'manual'
      query_clauses << 'match_status = "unmatchable"' if options[:match_statuses].include? 'unmatchable'
      query = query.where query_clauses.join(' OR ') unless query_clauses.empty?
    end

    if options[:q].present?
      string = ActiveSupport::Inflector.transliterate options[:q].downcase
      solr_result_ids = search {
        keywords string
        order_by :id
        paginate :per_page => 5_000
      }.results.map &:id
      query = query.where('bolton_references.id' => solr_result_ids).paginate(:page => options[:page])
    end

    query
  end

  def set_match
    if matches.size == 1 && matches.first.similarity >= 0.8
      self.match = matches.first.reference
      self.match_status = 'auto'
    else
      self.match = nil
      self.match_status = nil
    end
    save!
  end

  def update_match
    set_match if match_status == nil || match_status == 'auto'
  end

  def set_match_manually string
    if string == 'unmatchable'
      self.match = nil
      self.match_status = 'unmatchable'
    elsif string
      self.match = ::Reference.find string.to_i
      self.match_status = 'manual'
    else
      self.match = nil
      self.match_status = nil
    end
    save!
  end

  def self.set_matches
    all.each {|e| e.set_match}
  end

  def to_s
    "#{authors} #{citation_year}. #{title}."
  end

  def best_match_similarity
    matches.first && matches.first.similarity
  end

  def possible_matches_with_matched_first
    (possible_matches + [match]).uniq.compact.partition {|m| m == match}.flatten
  end

  def self.match_status_auto_count
    where(:match_status => 'auto').count
  end

  def self.match_status_manual_count
    where(:match_status => 'manual').count
  end

  def self.match_status_none_count
    where(:match_status => nil).count
  end

  def self.match_status_unmatchable_count
    where(:match_status => 'unmatchable').count
  end

  # ReferenceComparable
  def author; authors.split(',').first; end
  def type; reference_type; end

  def key
    @key ||= Bolton::ReferenceKey.new authors, citation_year
  end

  def self.set_key_caches
    all.each do |reference|
      reference.set_key_cache
      reference.save!
    end
  end

  def set_key_cache
    self.key_cache = key.to_s :db
  end

  def set_year
    self.year = ::Reference.citation_year_to_year citation_year
  end

  def self.normalize_to_see_if_anything_important_changed string
    return unless string
    original_string = string.dup
    string = string.gsub /<span.*?>.*?<\/span>/, ''
    string = string.gsub /\s/, ''
    if string =~ /<\/?span/
      require 'ruby-debug';debugger;'';
    end
    string
  end

  def self.import_update reference, attributes
    nothing_important_changed = normalize_to_see_if_anything_important_changed(reference.original) == normalize_to_see_if_anything_important_changed(attributes[:original])
    Progress.puts "Changed: #{reference.original}" unless nothing_important_changed
    reference.update_attributes attributes.merge(:import_result => nothing_important_changed ? 'updated_spans_removed' : 'updated')
    Progress.puts "To:      #{attributes[:original]}" unless nothing_important_changed
    Progress.puts unless nothing_important_changed
  end

  def self.import_updated_title reference, attributes
    Progress.puts "Updated title for #{reference}"
    Progress.puts "From: #{reference.title}"
    Progress.puts "To:   #{attributes[:title]}"
    Progress.puts
    reference.update_attributes attributes.merge(:import_result => 'updated_title')
  end

  def self.import_updated_authors reference, attributes
    Progress.puts "Updated authors for #{reference}"
    Progress.puts "From: #{reference.authors}"
    Progress.puts "To:   #{attributes[:authors]}"
    Progress.puts
    reference.update_attributes attributes.merge(:import_result => 'updated_authors')
  end

  def self.import_updated_year reference, attributes
    Progress.puts "Updated year for #{reference}"
    Progress.puts "From #{reference.citation_year} to #{attributes[:citation_year]}"
    Progress.puts
    reference.update_attributes attributes.merge(:import_result => 'updated_year')
  end

  def self.import attributes
    attributes[:title] = attributes[:title][0, 255]
    if reference = where(attributes).first
      reference.update_attribute :import_result, 'identical'
    elsif reference = where(:authors => attributes[:authors], :citation_year => attributes[:citation_year], :title => attributes[:title]).first
      import_update reference, attributes
    elsif reference = where(:authors => attributes[:authors], :citation_year => attributes[:citation_year]).first
      import_updated_title reference, attributes
    elsif reference = where(:authors => attributes[:authors], :title => attributes[:title]).first
      import_updated_year reference, attributes
    elsif reference = where(:citation_year => attributes[:citation_year], :title => attributes[:title]).first
      import_updated_authors reference, attributes
    else
      reference = create! attributes.merge(:import_result => 'added')
    end
    reference
  end

end

app/models/hol/reference.rb
# coding: UTF-8
class Hol::Reference < ::ComparableReference
  attr_accessor :document_url 
end

app/controllers/references_controller.rb
# coding: UTF-8
class ReferencesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :download]
  skip_before_filter :authenticate_user!, :if => :preview?

  def index
    searching = params[:q].present?
    params[:search_selector] ||= 'Search for'
    if ['review', 'new', 'clear'].include? params[:commit]
      params[:q] = ''
    end
    params[:q].strip! if params[:q]
    params[:review] = params[:commit] == 'review'
    params[:whats_new] = params[:commit] == 'new'

    @endnote_export_confirmation_message = <<EOS
AntCat will download these references to a file named "antcat_references.utf8.endnote_import". When your browser asks, save this file. Then use EndNote's Import function on its File menu to import the file. Choose "EndNote Import" from Import Options, and "Unicode (UTF-8)" as the Text Translation.
EOS
    unless searching
      @endnote_export_confirmation_message << "\nSince there are no search criteria, AntCat will download all ten thousand references. This will take several minutes."
    end

    params[:is_author_search] = params[:search_selector] == 'Search for author(s)'

    respond_to do |format|
      format.html   {
        @references = Reference.do_search params
      }
      format.endnote_import  {
        references = Reference.do_search params.merge :format => :endnote_import
        render text: Exporters::Endnote::Formatter.format(references)
      }
    end
  end

  def download
    document = ReferenceDocument.find params[:id]
    if document.downloadable_by? current_user
      redirect_to document.actual_url
    else
      head 401
    end
  end

  def create
    @reference = new_reference
    save true
  end

  def update
    @reference = get_reference
    save false
  end

  def save new
    begin
      Reference.transaction do
        clear_document_params_if_necessary
        clear_nested_reference_id unless @reference.kind_of? NestedReference
        parse_author_names_string
        set_journal if @reference.kind_of? ArticleReference
        set_publisher if @reference.kind_of? BookReference
        set_pagination
        # kludge around Rails 3 behavior that uses the type to look up a record - so you can't update the type!
        Reference.connection.execute "UPDATE `references` SET type = '#{@reference.type}' WHERE id = '#{@reference.id}'" unless new
        @reference.update_attributes params[:reference]

        @possible_duplicate = @reference.check_for_duplicate unless params[:possible_duplicate].present?
        unless @possible_duplicate
          @reference.save!
          set_document_host
        end

        raise ActiveRecord::RecordInvalid.new @reference unless @reference.errors.empty?
      end
    rescue ActiveRecord::RecordInvalid
      @reference[:id] = nil if new
      @reference.instance_variable_set :@new_record, new
    end
    render_json new
  end

  def destroy
    @reference = Reference.find(params[:id])
    if @reference.destroy
      json = {:success => true}
    else
      json = {:success => false, :message => @reference.errors[:base]}.to_json
    end
    render :json => json
  end

  private
  def set_pagination
    params[:reference][:pagination] =
      case @reference
      when ArticleReference then params[:article_pagination]
      when BookReference then params[:book_pagination]
      else nil
      end
  end

  def set_document_host
    @reference.document_host = request.host
  end

  def parse_author_names_string
    author_names_and_suffix = @reference.parse_author_names_and_suffix params[:reference].delete(:author_names_string)
    @reference.author_names.clear
    params[:reference][:author_names] = author_names_and_suffix[:author_names]
    params[:reference][:author_names_suffix] = author_names_and_suffix[:author_names_suffix]
  end

  def set_journal
    params[:reference][:journal] = Journal.import params[:journal_name]
  end

  def set_publisher
    publisher_string = params[:publisher_string]
    publisher = Publisher.import_string publisher_string
    if publisher.nil? and publisher_string.present?
      @reference.errors.add :publisher_string, "Publisher string couldn't be parsed. In general, use the format 'Place: Publisher'. Otherwise, please post a message on http://groups.google.com/group/antcat/, and we'll see what we can do!"
      @publisher_string = publisher_string
      raise ActiveRecord::RecordInvalid.new @reference
    end
    params[:reference][:publisher] = publisher
  end

  def clear_nested_reference_id
    params[:reference][:nested_reference_id] = nil
  end

  def clear_document_params_if_necessary
    params[:reference][:document_attributes][:id] = nil unless params[:reference][:document_attributes][:url].present?
  end

  def render_json new = false
    json = {
      :isNew => new,
      :content => render_to_string(:partial => params[:picker].present? ? 'reference_pickers/reference' : 'references/reference',
                                   :locals => {:reference => @reference, :publisher_string => @publisher_string, :css_class => 'reference'}),
      :id => @reference.id,
      :success => @reference.errors.empty?
    }.to_json

    json = '<textarea>' + json + '</textarea>' unless Rails.env.test?
    render :json => json, :content_type => 'text/html'
  end

  def new_reference
    case params[:selected_tab]
    when 'Article' then ArticleReference.new
    when 'Book' then    BookReference.new
    when 'Nested' then  NestedReference.new
    else                UnknownReference.new
    end
  end

  def get_reference
    selected_tab = params[:selected_tab]
    selected_tab = 'Unknown' if selected_tab == 'Other'
    type = selected_tab + 'Reference'
    reference = Reference.find(params[:id]).becomes((type).constantize)
    reference.type = type
    reference
  end

end

app/helpers/reference_helper.rb
# coding: UTF-8
module ReferenceHelper
  def format_reference reference
    Formatters::ReferenceFormatter.format reference
  end

  def format_reference_document_link reference
    Formatters::CatalogFormatter.format_reference_document_link reference, current_user
  end

  def format_reference_document_link reference
    Formatters::CatalogFormatter.format_reference_document_link reference, current_user
  end

  def italicize string
    Formatters::ReferenceFormatter.italicize string
  end

  def format_timestamp timestamp
    Formatters::ReferenceFormatter.format_timestamp timestamp
  end
end

app/views/references/_edit.html.haml
- reference ||= Reference.new
- publisher_string ||= reference.respond_to?(:publisher) ? (reference.publisher && reference.publisher.to_s) : ''
- journal_name = reference.respond_to?(:journal) ? (reference.journal && reference.journal.name) : ''
- selected_tab = [ArticleReference, BookReference, NestedReference, UnknownReference].index(reference.class) || 0

.reference_edit.ui-corner-all.ui-widget-content.ui-widget
  - url = reference.new_record? ? references_path : reference_path
  - method = reference.new_record? ? 'post' : 'put'
  - html_options = Rails.env.test? ? {} : {:multipart => true}
  = form_for reference, :as => :reference, :url => url, :html => html_options do |f|
    %input{:type => 'hidden', :name => '_method', :value => method}
    %input{type: :hidden, name: :selected_tab, id: :selected_tab, class: :selected_tab, value: selected_tab}
    %input{type: 'hidden', name: 'possible_duplicate', id: 'possible_duplicate', value: @possible_duplicate ? 'true' : nil}
    = render 'shared/errors_for', :resource => reference

    %table
      %col{:width => '50px'}
      %col{:width => '*'}
      %col{:align => 'right', :width => '34px'}
      %col{:width => '100px'}
      %tr
        %td= label_tag :reference_author_names_string, 'Authors'
        %td.authors= f.text_field :author_names_string, :class => 'authors'
        %td{:style => 'padding-right: 5px'}= label_tag :reference_citation_year, 'Year'
        %td{:class => :right_side_field}= f.text_field :citation_year
      %tr
        %td= label_tag :reference_title, 'Title'
        %td{:colspan => 3, :class => :right_side_field}= f.text_area :title, :rows => 2
      %tr
        %td.tabs{:colspan => 4}
          %ul
            %li
              %a{:class => 'article-tab', :href => "#tabs-article-#{reference.id}"}Article
            %li
              %a{:class => 'book-tab', :href => "#tabs-book-#{reference.id}"}Book
            %li
              %a{:class => 'nested-tab', :href => "#tabs-nested-#{reference.id}"}Nested
            %li
              %a{:class => 'unknown-tab', :href => "#tabs-unknown-#{reference.id}"}Other

          %div{:class => 'article-tab-section', :id => "tabs-article-#{reference.id}"}
            = label_tag :journal_name, 'Journal'
            = text_field_tag :journal_name, journal_name, :class => 'journal'
            = label_tag :reference_series_volume_issue, 'Series volume issue'
            = f.text_field :series_volume_issue, :class => 'series_volume_issue'
            = label_tag :article_pagination, 'Pagination'
            = text_field_tag :article_pagination, reference.pagination, :class => 'pages'

          %div{:class => 'book-tab-section', :id => "tabs-book-#{reference.id}"}
            = label_tag :publisher_string, 'Publisher'
            = text_field_tag :publisher_string, publisher_string, :class => 'publisher'
            = label_tag :book_pagination, 'Pagination'
            = text_field_tag :book_pagination, reference.pagination, :class => 'pages'

          %div{:class => 'nested-tab-section', :id => "tabs-nested-#{reference.id}"}
            = label_tag :reference_pages_in, 'Pages in'
            = f.text_field :pages_in, :class => 'pages'
            = label_tag :reference_nested_reference_id, 'Nested reference ID'
            = f.text_field :nested_reference_id, :class => 'pages'
            %p.help
              %span.help= raw "To find, edit or add the nested reference in a new browser window, click #{link_to 'here', references_path(:q => reference.nested_reference_id), :target => '_blank'}"

          %div{:class => 'unknown-tab-section', :id => "tabs-unknown-#{reference.id}"}
            = label_tag :reference_citation, 'Citation'
            = f.text_area :citation, :rows => 2

      = f.fields_for :document, reference.document || ReferenceDocument.new do |document_form|
        %tr
          %td= label_tag :document_url, 'Source URL'
          %td{:colspan => 3, :class => :right_side_field}
            = document_form.text_field :url
            = label_tag :document_public, 'Internal but public?'
            = document_form.check_box :public
        - unless $ReleaseType.preview?
          %tr
            %td= label_tag :document_file, 'Upload'
            %td= document_form.file_field :file

      %tr
        %td= label_tag :reference_public_notes, 'Public notes'
        %td{:colspan => 3, :class => :right_side_field}= f.text_area :public_notes, :rows => 2
      - if user_is_editor?
        %tr
          %td= label_tag :reference_editor_notes, 'Editor notes'
          %td{:colspan => 3, :class => :right_side_field}= f.text_area :editor_notes, :rows => 2
        %tr
          %td= label_tag :reference_taxonomic_notes, 'Taxonomic notes'
          %td{:colspan => 3, :class => :right_side_field}= f.text_area :taxonomic_notes, :rows => 2
      %tr
        %td{:colspan => 4}
          %table.small_fields
            %tr
              %td{:style => 'padding-right: 5px'}= label_tag :reference_cite_code, 'Cite code'
              %td.cite_code= f.text_field :cite_code
              %td= label_tag :reference_possess, 'Possess'
              %td.possess= f.text_field :possess
              %td= label_tag :reference_date, 'Date'
              %td.date= f.text_field :date
              %td= label_tag :reference_id, 'ID'
              %td= reference.id
      %tr
        %td{:colspan => 4}
          %button.submit= previewize @possible_duplicate ? 'Save Anyway' : 'Save'
          %button.cancel Cancel
          %button.delete= previewize 'Delete'

app/views/references/_form.html.haml
- reference ||= Reference.new
- publisher_string = reference.respond_to?(:publisher) ? (reference.publisher && reference.publisher.to_s) : ''
- journal_title = reference.respond_to?(:journal) ? (reference.journal && reference.journal.title) : ''
- selected_tab = [ArticleReference, BookReference, OtherReference].index(reference.class) || 0

.reference_form.ui-corner-all.ui-widget-content.ui-widget
  - url = reference.new_record? ? references_path : reference_path(reference)
  - method = reference.new_record? ? 'post' : 'put'
  - form_for :reference, reference, :url => url do |f|
    %input{:type => 'hidden', :name => '_method', :value => method}
    %input{:type => 'hidden', :class => 'selected_tab', :value => selected_tab}
    = render :partial => 'shared/errors_for', :locals => { :resource => reference }

    %table
      %col{:width => '50px'}
      %col{:width => '*'}
      %col{:align => 'right', :width => '34px'}
      %col{:width => '100px'}
      %tr
        %td Authors
        %td.authors= f.text_field :authors_string, :class => 'authors'
        %td{:style => 'padding-right: 5px'} Year
        %td{:class => :right_side_field}= f.text_field :citation_year
      %tr
        %td Title
        %td{:colspan => 3, :class => :right_side_field}= f.text_area :title, :rows => 2
      %tr
        %td.tabs{:colspan => 4}
          %ul
            %li
              %a{:class => 'article-tab', :href => "#tabs-article-#{reference.id}"}Article
            %li
              %a{:class => 'book-tab', :href => "#tabs-book-#{reference.id}"}Book
            %li
              %a{:class => 'other-tab', :href => "#tabs-other-#{reference.id}"}Other

          %div{:class => 'article-tab-section', :id => "tabs-article-#{reference.id}"}
            Journal
            = text_field_tag :journal_title, journal_title, :class => 'journal'
            Series volume issue
            = f.text_field :series_volume_issue, :class => 'series_volume_issue'
            Pages
            = text_field_tag :article_pagination, reference.pagination, :class => 'pages'

          %div{:class => 'book-tab-section', :id => "tabs-book-#{reference.id}"}
            Publisher
            = text_field_tag :publisher_string, publisher_string, :class => 'publisher'
            Pages
            = text_field_tag :book_pagination, reference.pagination, :class => 'pages'

          %div{:class => 'other-tab-section', :id => "tabs-other-#{reference.id}"}
            Citation
            = f.text_area :citation, :rows => 2

      %tr
        %td Source URL
        %td{:colspan => 3, :class => :right_side_field}= f.text_field :source_url
      %tr
        %td Public notes
        %td{:colspan => 3, :class => :right_side_field}= f.text_area :public_notes, :rows => 2
      %tr
        %td Editor notes
        %td{:colspan => 3, :class => :right_side_field}= f.text_area :editor_notes, :rows => 2
      %tr
        %td Taxonomic notes
        %td{:colspan => 3, :class => :right_side_field}= f.text_area :taxonomic_notes, :rows => 2
      %tr
        %td{:colspan => 4}
          %table.small_fields
            %tr
              %td{:style => 'padding-right: 5px'} Cite code
              %td.cite_code= f.text_field :cite_code
              %td Possess
              %td.possess= f.text_field :possess
              %td Date
              %td.date= f.text_field :date
      %tr
        %td{:colspan => 4}
          %button.submit Save
          %button.cancel Cancel
          %button.delete Delete

app/views/references/_reference.html.haml
-#Locals: reference, edit_template_directory

- reference ||= Reference.new
- id = "reference_#{reference.id}"
- css_class << ' ' << id
%div{id: id, class: css_class, 'data-reference-id' => reference.id, 'data-taxt' => Taxt.to_editable_reference(reference)}
  %table.reference_table
    %tr
      %td.icons
        %a.icon.edit{:title => 'edit', :href => '#'}
          = image_tag 'edit_off.png', :alt => 'edit'
        %a.icon.add{:title => 'add', :href => '#'}
          = image_tag 'add_off.png', :alt => 'add'
        %a.icon.copy{:title => 'copy', :href => '#'}
          = image_tag 'copy_off.png', :alt => 'copy'
        %a.icon.delete{:title => 'delete', :href => '#'}
          = image_tag 'delete_off.png', :alt => 'delete'
      %td.reference_item
        = render 'references/display', :reference => reference if !reference.new_record? && reference.errors.empty?
        - if user_can_edit?
          = render "#{edit_template_directory}/edit", :reference => reference, :publisher_string => publisher_string
        = render 'shared/coins', :reference => reference if !reference.new_record? && reference.errors.empty?

app/views/references/index.html.haml
- @title = 'Bibliography'

- content_for :head do
  = javascript_include_tag 'references', 'reference_autocompletion', 'qtip'

- content_for :page_header do
  #navigation_bar
    .actions
      - items = [link_to('Latest additions', references_path(:commit => 'new'))]
      - if user_can_edit?
        - items << link_to('Latest changes', references_path(:commit => 'review'))
        - items << link_to('Journals', journals_path)
      - items << link_to('Export to EndNote', endnote_import_path(:q => params[:q]), :confirm => @endnote_export_confirmation_message)
      = make_link_menu items

    = render 'search', :params => params

  .title
    %h2.left ANTBIB
    %h2.left A Bibliography of Ant Systematics
    %h3.right by Philip S. Ward, et al.
    .clear

-if @references.empty?
  .no_results_found
    No results found

%table.references

  - if params[:review]
    %tr
      %td
      %td.date_header
        Changed

  - if params[:whats_new]
    %tr
      %td
      %td.date_header
        Created

  - for reference in @references
    %tr.reference_row
      %td
        = render 'reference', :reference => reference, :publisher_string => @publisher_string, :css_class => 'reference'
      - if params[:review]
        %td.date
          = format_timestamp reference.updated_at
      - if params[:whats_new]
        %td.date
          = format_timestamp reference.created_at

  - if user_can_edit?
    %tr.reference_template_row
      %td
        = render 'reference', :reference => nil, :publisher_string => @publisher_string, :css_class => 'reference_template'

%div= will_paginate @references